channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - packaging==23.2
  - psutil==5.9.7
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - typing-extensions==4.11.0
name: mlflow-env
